version: "3.8"
services:
  localstack:
    image: localstack/localstack:0.14.0
    ports:
      - "4566:4566"
    environment:
      SERVICES: sqs,sns
      DEFAULT_REGION: eu-central-1

  postgres:
    image: postgres:12-alpine
    ports:
      - "5441:5432"
    environment:
      POSTGRES_PASSWORD: someLocalPassword
